default: &DEFAULT
  # Sent in emails to users
  application_name: 'Cateplaces'

  # User settings: controls whether send email and login after creation
  automatically_activate: false
  automatically_login_after_account_create: false

  flickr_key: '0cc5346a72937ee4c154eb29654f33f3'
  flickr_secret: 'f1acf911820c417a'
  flickr_cache: "#{RAILS_ROOT}/config/flickr.cache"
  google_analytics_key: 'UA-6093625-1'

  integrate_portfolio: false

  allow_following: false

  portfolio_url_template: "groups.luvfoo.com/Members/{user_login}/my-eportfolio/RSS"

  # complete url for website home (does not have to be the social network home)
  website_home_url: "http://railscode.mine.nu"

  # the platform is setup to work with the Plone CMS.
  integrate_plone: true
  plone_site: 'http://courses.luvfoo.com'

  # url of 'contact us' or 'feedback' for in the event that you don't want to use the default contact us form.
  use_external_contact_us: false
  contact_us_url: 'http://courses.luvfoo.com/feedback'

  # send an email to the user indicating that their account was successfully added.
  send_activated_email: false

  # START of "do not edit" session
  youtube_base_url: "http://gdata.youtube.com/feeds/api/videos/"
  default_locale: luvfoo
  # END of "do not edit" session

  # attachment_fu_options for uploads
  upload:
    missing_thumb: '/images/icon_missing_thumb.gif'
    missing_medium: "/images/icon_missing_medium.gif"
    attachment_fu_options:
      resize_to: "465>"
      min_size: 1    
      # size in megabytes
      max_size: 5
      thumbnails: {icon: "30x30!", thumb: "100x100!", small: "48x48>", medium: "290x320!", large: "664>"}
      #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
      storage: 'file_system'
      #content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']
      #processor: image_science

  automatically_activate: true
  automatically_login_after_account_create: true	
  use_recaptcha: true
  recaptcha_pub_key: 6LenNAMAAAAAALMFoPx63BDrQ7jQ7EaoYLO06p5f
  recaptcha_priv_key: 6LenNAMAAAAAAPMSO7SKmq7kJtYi6zDz9md5cOnL

##########################
# PRODUCTION settings
##########################
production:
  <<: *DEFAULT

  # for cookies that need to work across all subdomains (the plone site)
  application_base_url: 'railscode.mine.nu'
  assert_server_url: 'http://railscode.mine.nu'

  # sync user information to Salesforce.  This requires a salesforce account and key
  integrate_salesforce: false
  salesforce_owner_id: 'your-salesforce-id'

  # Text for emails - ie Sincerly, emailed_by
  emailed_by: 'Luvfoo Team'

  # email address for support requests
  support_email: 'info@luvfoo.com'

  # Source address for user emails
  email_from: 'info@luvfoo.com'

  # Destination email for system errors
  admin_email: 'admin@luvfoo.com'

  # Sent in emails to users
  application_url: 'railscode.mine.nu'
  mailer_to_address: 'info@luvfoo.com'

  # configuration for plone xml rpc call that creates user folders
  plone_xmlrpc_port: 8091    
  plone_xmlrpc_path: '/eduCommons'    
  plone_xmlrpc_server: "10.6.0.4"
    
##########################
# DEVELOPMENT settings
##########################
development:
  <<: *DEFAULT

  # for cookies that need to work across all subdomains (the plone site)
  application_base_url: 'localhost:3003'
  assert_server_url: 'http://localhost:3003'

  # sync user information to Salesforce.  This requires a salesforce account and key
  integrate_salesforce: false
  salesforce_owner_id: 'your-salesforce-id'

  # Text for emails - ie Sincerly, emailed_by
  emailed_by: 'Luvfoo Team'

  # email address for support requests
  support_email: 'info@luvfoo.com'

  # Source address for user emails
  email_from: 'info@luvfoo.com'

  # Destination email for system errors
  admin_email: 'admin@luvfoo.com'

  # Sent in emails to users
  application_url: 'localhost:3003'
  mailer_to_address: 'info@luvfoo.com'

  # configuration for plone xml rpc call that creates user folders
  plone_xmlrpc_port: 80
  plone_xmlrpc_path: '/RPC2'
  plone_xmlrpc_server: "courses.luvfoo.com"

##########################
# TEST settings
##########################
test:
  <<: *DEFAULT

  # for cookies that need to work across all subdomains (the plone site)
  application_base_url: 'localhost:3002'
  assert_server_url: 'http://localhost:3002'

  # sync user information to Salesforce.  This requires a salesforce account and key
  integrate_salesforce: false
  salesforce_owner_id: 'your-salesforce-id'

  # Text for emails - ie Sincerly, emailed_by
  emailed_by: 'Luvfoo Team'

  # email address for support requests
  support_email: 'info@luvfoo.com'

  # Source address for user emails
  email_from: 'info@luvfoo.com'

  # Destination email for system errors
  admin_email: 'admin@luvfoo.com'

  # Sent in emails to users
  application_url: 'railscode.mine.nu'
  mailer_to_address: 'info@luvfoo.com'

  # configuration for plone xml rpc call that creates user folders
  plone_xmlrpc_port: 80
  plone_xmlrpc_path: '/RPC2'
  plone_xmlrpc_server: "courses.luvfoo.com"

